name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_region: "ap-southeast-1"
  TF_VAR_profile: "sheikh"

jobs:
  terraform:
    name: Apply and Destroy EC2 Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

#      - name: Terraform Plan
#        id: plan
#        run: terraform plan -out=tfplan


      - name: Terraform Plan
        id: plan
        run: |
          export TF_LOG=DEBUG
          terraform plan -out=tfplan


      - name: Terraform Apply
        if: github.event_name != 'pull_request'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy (for manual or scheduled runs)
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve
